const seededProducts = [
  {name:'Magnetic cable organizer',category:'home',tag:'Home & living',emoji:'🧲',tone:'linear-gradient(135deg,#dbe9d1,#b9d487)',cost:4.2,price:18.99,demand:88,competition:32,margin:77,channels:['shopify','amazon'],keywords:['practical','small-space','home','gift']},
  {name:'Travel jewelry case',category:'travel',tag:'Travel',emoji:'🧳',tone:'linear-gradient(135deg,#f4dfce,#e8b49a)',cost:6.8,price:24.99,demand:91,competition:38,margin:82,channels:['etsy','shopify'],keywords:['gift','travel','practical','eco']},
  {name:'Refillable pocket mist',category:'wellness',tag:'Wellness',emoji:'🫧',tone:'linear-gradient(135deg,#d7e9e3,#acd5c6)',cost:3.1,price:16.5,demand:79,competition:29,margin:81,channels:['shopify','etsy'],keywords:['wellness','eco','gift']},
  {name:'Slow-feeder lick mat',category:'pets',tag:'Pets',emoji:'🐾',tone:'linear-gradient(135deg,#f2e6c9,#dfc98e)',cost:5.5,price:21.99,demand:86,competition:42,margin:75,channels:['amazon','shopify'],keywords:['pet','practical','gift']},
  {name:'Under-sink storage rack',category:'home',tag:'Home & living',emoji:'🧺',tone:'linear-gradient(135deg,#e6dfd6,#c5b7a5)',cost:9.2,price:29.99,demand:84,competition:51,margin:69,channels:['amazon','shopify'],keywords:['home','small-space','practical']},
  {name:'Cooling eye patches',category:'beauty',tag:'Beauty',emoji:'✨',tone:'linear-gradient(135deg,#e8e0f3,#c4b4e4)',cost:2.4,price:14.99,demand:82,competition:35,margin:84,channels:['etsy','shopify'],keywords:['beauty','wellness','gift']},
  {name:'Linen market tote',category:'travel',tag:'Travel',emoji:'👜',tone:'linear-gradient(135deg,#e9e1cf,#c9b88e)',cost:7.3,price:26,demand:75,competition:36,margin:72,channels:['etsy','shopify'],keywords:['eco','travel','gift']},
  {name:'Desk focus timer',category:'wellness',tag:'Wellness',emoji:'⏱️',tone:'linear-gradient(135deg,#d9e1ee,#a9bddc)',cost:8.5,price:31.99,demand:78,competition:44,margin:73,channels:['amazon','shopify'],keywords:['practical','wellness','home']},
  {name:'Ceramic plant mister',category:'home',tag:'Home & living',emoji:'🌱',tone:'linear-gradient(135deg,#dcebd8,#a9ce9d)',cost:5.9,price:22.5,demand:73,competition:31,margin:74,channels:['etsy','shopify'],keywords:['home','gift','eco']}
];
seededProducts.forEach((p,i)=>Object.assign(p,{trend:p.trend??[94,97,89,86,78,92,81,76,72][i],velocity:p.velocity??['+42%','+56%','+31%','+38%','+19%','+48%','+24%','+17%','+12%'][i],risk:p.risk??(['Low','Low','Low','Medium','Medium','Medium','Low','Medium','Low'][i]),action:p.action??(['Order a 20-unit test','Test 3 creative angles','Validate refill repeat rate','Check material compliance','Model shipping before test','Verify claims + shelf life','Bundle with a pouch','Test higher AOV bundle','Lead with gifting angle'][i])}));
const products=[];
const readSet=(key,fallback)=>new Set(JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback)));
const state={saved:readSet('scoutly-saved',['Magnetic cable organizer','Travel jewelry case','Refillable pocket mist']),visible:6,approved:readSet('scoutly-approved',[]),passed:readSet('scoutly-passed',[]),planCreated:localStorage.getItem('scoutly-plan-created')==='true'};
const $=s=>document.querySelector(s);
function score(p){return Math.round((p.demand*.38)+(p.margin*.26)+(p.trend*.2)+((100-p.competition)*.16))}
function roi(p){return Math.round(((p.price-p.cost)/p.cost)*100)}
function money(n){return '$'+n.toFixed(2)}
function currentKeywords(){return ($('#queryInput').value.toLowerCase().match(/[a-z]+(?:-[a-z]+)?/g)||[])}
function render(){
  const channel=$('#channel').value, category=$('#category').value, budget=Number($('#budget').value), floor=Number($('#roiFloor').value), keywords=currentKeywords();
  let list=products.filter(p=>p.cost*20<=budget && roi(p)>=floor && (category==='all'||p.category===category) && (channel==='all'||p.channels.includes(channel)));
  list=list.map(p=>({...p,opportunity:score(p),roi:roi(p),relevance:keywords.filter(k=>p.keywords.some(x=>x.includes(k)||k.includes(x))).length}));
  if(keywords.length) list.sort((a,b)=>(b.relevance-a.relevance)||(b.opportunity-a.opportunity));
  const sort=$('#sort').value;if(sort==='margin')list.sort((a,b)=>b.margin-a.margin);if(sort==='demand')list.sort((a,b)=>b.demand-a.demand);if(sort==='roi')list.sort((a,b)=>b.roi-a.roi);if(sort==='score')list.sort((a,b)=>b.opportunity-a.opportunity);
  const shown=list.slice(0,state.visible);$('#resultCount').textContent=list.length;$('#qualifiedCount').textContent=list.length;$('#avgRoi').textContent=list.length?Math.round(list.reduce((sum,p)=>sum+p.roi,0)/list.length)+'%':'—';$('#results').innerHTML=shown.map((p,i)=>`<article class="result-card" style="animation-delay:${i*45}ms"><div class="product-image" style="background:${p.tone}"><span class="product-emoji">${p.emoji}</span><button class="save-button ${state.saved.has(p.name)?'saved':''}" data-save="${p.name}" aria-label="Save ${p.name}">${state.saved.has(p.name)?'♥':'♡'}</button></div><div class="card-meta"><span class="category-tag">${p.tag}</span><span class="score">${p.opportunity}% scale fit</span></div><h3>${p.name}</h3><div class="metrics"><div class="metric"><span>ROI POTENTIAL</span><strong class="good">${p.roi}%</strong></div><div class="metric"><span>VELOCITY</span><strong>${p.velocity}</strong></div><div class="metric"><span>RISK</span><strong>${p.risk}</strong></div></div><div class="next-action"><span>NEXT MOVE</span><strong>${p.action}</strong></div></article>`).join('');$('#emptyState').classList.toggle('hidden',shown.length>0);$('#loadMore').classList.toggle('hidden',list.length<=state.visible);$('#savedCount').textContent=state.saved.size;
}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function renderQueue(){const floor=Number($('#roiFloor').value);const queue=products.filter(p=>roi(p)>=floor&&!state.passed.has(p.name)).slice(0,3);const approved=[...state.approved].map(name=>products.find(p=>p.name===name)).filter(Boolean);$('#queueCount').textContent=queue.filter(p=>!state.approved.has(p.name)).length;$('#approvalQueue').innerHTML=queue.map(p=>`<div class="approval-row ${state.approved.has(p.name)?'approved':''}"><div class="approval-product"><span class="approval-emoji">${p.emoji}</span><div><strong>${p.name}</strong><small>${p.tag} · ${roi(p)}% product ROI · ${p.risk} risk</small></div></div><div class="approval-action">${state.approved.has(p.name)?'<span class="approved-label">Test approved ✓</span>':`<button class="pass-button" data-pass="${p.name}">Pass</button><button class="approve-button" data-approve="${p.name}">Approve test ↗</button>`}</div></div>`).join('');const plan=$('#testPlan');plan.classList.toggle('hidden',approved.length===0);if(approved.length){$('#testPlanTitle').textContent=state.planCreated?'Test plan ready for '+approved[0].name:'Build a test plan for '+approved[0].name;$('#launchPlan').textContent=state.planCreated?'Test plan created ✓':'Create test plan ↗';$('#launchPlan').disabled=state.planCreated}}
$('#scoutButton').addEventListener('click',()=>{state.visible=6;render();renderQueue();toast('Scoutly refreshed your shortlist ✦')});
['channel','category','experience','sort','roiFloor'].forEach(id=>$('#'+id).addEventListener('change',()=>{state.visible=6;render();renderQueue()}));
$('#budget').addEventListener('input',e=>{$('#budgetValue').textContent=e.target.value==='1000'?'Under $1,000':'Under $'+e.target.value;state.visible=6;render()});
$('#results').addEventListener('click',e=>{const button=e.target.closest('[data-save]');if(!button)return;const name=button.dataset.save;if(state.saved.has(name)){state.saved.delete(name);toast('Removed from saved ideas')}else{state.saved.add(name);toast('Saved to your idea board ♥')}render()});
$('#approvalQueue').addEventListener('click',e=>{const approve=e.target.closest('[data-approve]');const pass=e.target.closest('[data-pass]');if(approve){state.approved.add(approve.dataset.approve);localStorage.setItem('scoutly-approved',JSON.stringify([...state.approved]));toast('Test approved — ready for supplier review');renderQueue()}if(pass){state.passed.add(pass.dataset.pass);localStorage.setItem('scoutly-passed',JSON.stringify([...state.passed]));toast('Opportunity passed');renderQueue()}});
$('#launchPlan').addEventListener('click',()=>{state.planCreated=true;localStorage.setItem('scoutly-plan-created','true');renderQueue();toast('Test plan created — supplier review is next')});
document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>{$('#queryInput').value=button.dataset.prompt;render();toast('Prompt applied — shortlist updated')}));
$('#loadMore').addEventListener('click',()=>{state.visible+=3;render()});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#queryInput').focus()}});
let seconds=299;let autopilot=true;setInterval(()=>{if(!autopilot)return;seconds=seconds<=0?299:seconds-1;const min=String(Math.floor(seconds/60)).padStart(2,'0');const sec=String(seconds%60).padStart(2,'0');$('#nextScan').textContent=`${min}:${sec}`},1000);
$('#autopilotToggle').addEventListener('click',()=>{autopilot=!autopilot;const button=$('#autopilotToggle');button.classList.toggle('on',autopilot);button.querySelector('span:last-child').textContent=autopilot?'Autopilot on':'Autopilot paused';toast(autopilot?'Autopilot resumed — scanning every 5 minutes':'Autopilot paused')});
render();renderQueue();
async function loadSourceStatus(){const target=$('#sourceStatus');try{const response=await fetch('/api/status');const data=await response.json();target.innerHTML=Object.entries(data.sources).map(([key,source])=>`<div class="source-card ${source.connected?'connected':'missing'}"><span class="source-dot"></span><div><strong>${source.name}</strong><small>${source.connected?source.description:'Not connected — no data will be displayed'}</small></div><span class="source-state">${source.connected?'CONNECTED':'REQUIRED'}</span></div>`).join('');$('#truthMessage').textContent=data.ready?'Live sources connected. Every displayed fact will carry its source and retrieval time.':'No live source is connected. Scoutly is in evidence-only mode and will not display product claims.'}catch(error){target.innerHTML='<div class="source-card missing"><span class="source-dot"></span><div><strong>Live source gateway unavailable</strong><small>Start the Scoutly server with the configured credentials.</small></div><span class="source-state">OFFLINE</span></div>';$('#truthMessage').textContent='The live source gateway is offline. No product data is being shown.'}}
loadSourceStatus();
